### ISSUE TITLE
[Q] About ESP3D wifi

### ISSUE THREAD

**Issue by simonwebnet** [Guilouz/BTT-TFT70-SuperRacer#10]
Hi, 
with firmware from Pack Super Racer - BigTreeTech TFT70 version Marlin 2.0.9.3 - FLSUN SR - BTT TFT - NanoV3 - LGX Lite 
is possible add the usage of ESP3D or there are problems with available serial ports?
If yes how I need to configure the ports in marlin and other stuff related to wifi before recompile?
Your firmware is a great job!

Simon

**Comment by Guilouz** [comment]
Hi, you just need to enable 2nd serial port in config.ini file of TFT and reflash it.

```
#### Serial Ports (Primary and Supplementary)
# Serial ports connected to devices such as Printer, ESP3D, OctoPrint and other Controllers.
# In order to successfully establish a communication through a serial port, set a baudrate
# matching the baudrate configured on the connected device.
# Disable the serial port when it is not in use and/or not connected to a device (floating) to
# avoid to receive and process wrong data due to possible electromagnetic interference (EMI).
#
# NOTES:
#   - Serial port P1 is the primary serial connection to the printer and cannot be disabled.
#   - A baudrate of 250000 works in most cases, but you can try a lower speed if you
#     commonly experience drop-outs during host printing.
#     You may try up to 1000000 to speed up SD file transfer.
#
#   Format: [serial_port: P1:<baudrate> P2:<baudrate> P3:<baudrate> P4:<baudrate>
#   Target port: P1: Printer
#                P2: WIFI    (e.g. ESP3D)
#                P3: UART 3  (e.g. OctoPrint)
#                P4: UART 4
#   Value range: P1: [min: 1, max: 9]
#                P2: [min: 0, max: 9]
#                P3: [min: 0, max: 9]
#                P4: [min: 0, max: 9]
#   Options: [OFF (port disabled): 0, 2400: 1, 9600: 2, 19200: 3, 38400: 4, 57600: 5, 115200: 6, 250000: 7, 500000: 8, 1000000: 9]
serial_port:P1:7 P2:0 P3:0 P4:0
```

**Comment by simonwebnet** [comment]
Ok super speed answer! 
And nothing to do on the marlin side of robin nano? 
Before install the module on the printer with TFT I want test wifi communication functionality via terminal on a Robin nano V3.1 free and alone, powered via usb power bank.

**Comment by Guilouz** [comment]
No nothing else.

**Comment by simonwebnet** [comment]
Hi, 
another little question: your answers (both) was intended for ESP 12 (now I'm trying an ESP 12s on the board without TFT with no results in serial communication but wifi and WEBUI are ok) or for ESP01 mounted on the TFT?
