### ISSUE TITLE
Is it possible to use other BTT tft screens and your screen firmware 

### ISSUE THREAD

**Issue by Bluez-Printz** [Guilouz/BTT-TFT70-SuperRacer#11]
Hey im currently running your firmware on my SR (love it btw thank you so much for your hard work ) . I was wondering about the tft 70 screen firmware . Is it possible to use a btt tft 35 screen instead of a tft 70 if i replace the TFT70 folder in the firmware pack to tft 35 from BTT github page while using our config.ini and .bin file . The TFT70 is about 200 plus tax and 2 months shipping here where the TFT35 is around 70 and a week . Thanks so much in advance , hope that makes sense to you

**Comment by Guilouz** [comment]
Yes you can use TFT35 if you want, but you need to recompile my firmware for it and use TFT35 folder.

You must use my firmware and not only config.ini because firmware is configured for delta printer in Configuration.h inside firmware.

**Comment by Bluez-Printz** [comment]
ok that makes sense tho i was hoping to avoid compiling as i have only briefly touched vsstudio . is there a screen option in the mks line thats a direct replacement without having to recompile ? I saw a comment you made in a group about how the stock screen deals with the z height improperly and wanted a new screen for that aspect alone

**Comment by bankm1** [comment]
I made a few attempts to recompile for the TFT35. It compiled without errors & successfully flashed it to my btt tft35. However, it doesn't control the printer. It connects to my SR, reads temp sesnors & I can see messages coming from the printer in the console page of the tft35. But thats it. Nothing else works. Im doing something wrong when compiling the code. Thanks to the Dev for all your work. I'll keep trying until I can make it functional

**Comment by Guilouz** [comment]
Is it ok ?
