### ISSUE TITLE
The fans no longer work with the latest version.

### ISSUE THREAD

**Issue by nlenaerts** [Guilouz/BTT-TFT70-SuperRacer#2]
Hello, 

before I used a version of the screen and motherboard firmware downloaded on January 3, today I updated the firmware but since then the fans no longer work. When I change the value from the screen, I see the fan1 light come on but when I plug into fan1 they don't work in pwm.

Do you have any idea where this problem could come from?

Thanks in advance.
Nicolas

**Comment by nlenaerts** [comment]
It seems that the problem does not come from the firmware of the screen but rather from that of the motherboard

**Comment by nlenaerts** [comment]
I compared the sources of the version I was using and the last one and I think the problem comes from the values ​​in this file --> /Sources/Marlin/src/pins/stm32f4/pins_MKS_ROBIN_NANO_V3_common.h
[![Capture-d-e-cran-2022-02-16-a-13-34-45.png](https://i.postimg.cc/L5kYjVr0/Capture-d-e-cran-2022-02-16-a-13-34-45.png)](https://postimg.cc/Pvx5j1fm)

**Comment by Guilouz** [comment]
Yes, it's a mistkake, I have updated package.

**Comment by nlenaerts** [comment]
I confirm that the problem is fixed with the latest version.
