### ISSUE TITLE
Décalage de Z

### ISSUE THREAD

**Issue by atraxxx73** [Guilouz/BTT-TFT70-SuperRacer#3]
Bonjour, 
J ai upgrade ma SR il y a deux jours, avec un tft 70, firmware TFT70 - 26/03/2022.
Extrudeur stock.
Je tranche sous cura, profil SR fournit par ce dernier, pas de modif a part un G55 dans le start gcode.
Calibration extrudeur faite, les PID, le G33, l ABL et le Z offset également.
J ai voulu lancer ce matin un cube de calibration, je le tranche normalement, le met sur clé usb, en fichier flsun pour tester la prévisualisation, met la clé usb sur le port usb du tft et lance tout ça.
Au départ de l'impression, ma tête d'impression fait des sursauts pendant la purge d'environ 1mm, puis l'ensemble se relève d'environ 2mm dès le début d'impression.
J'ai testé le port SD du TFT, le port sd de la CM, même soucis.
J'ai testé de changer de fichier, de l'enregistrer directement en format GCODE, même soucis.
Je me tourne maintenant vers un soucis de profile CURA, mais celui ci fonctionnait avec l'imprimante stock.
Je ne sais plus ou chercher, aurais tu une idée?

**Comment by Guilouz** [comment]
Si tu peux me faire une vidéo de ton problème.
Et vérifie également la planéité de ton bed avec une règle une fois bien chaud.

**Comment by atraxxx73** [comment]
Je suis désolé de t’embêter avec mes soucis, je ne sais juste pas trop par ou commencer. Est ce que c'est un problème de profil cura, un problème de start G code. J'avais vu sur la vidéo de Jocelyn qu'il y avait un G Code spécifique de start et de end, mais j'ai vu qu'il avait disparu dans la description des releases.
Et à la vue de la réaction de la tête, je pencherais bien pour un truc qui me met le caca dans les Gcodes.
Donc voici la vidéo du comportement de la bécane. Je regarde la planéïté de plateau cet après midi.
https://www.youtube.com/watch?v=ipVtFIpoUoc

**Comment by Guilouz** [comment]
Le start Gcode à utiliser est toujours présent ici : https://github.com/Guilouz/Marlin-SuperRacer-SKR2.0-LGX-Lite/blob/main/README.md

Testes-le et vois si ça fait la même chose.

**G-Code de démarrage :**

`G21 ; Unités en millimètres`<br />
`G90 ; Positionnement absolu`<br />
`M82 ; Axe E en mode absolu`<br />
`M140 S{material_bed_temperature} ; Température du plateau` (pour Cura)<br />
`M104 S{material_print_temperature} ; Température de la buse` (pour Cura)<br />
`M190 S{material_bed_temperature} ; Attente la température du plateau` (pour Cura)<br />
`M109 S{material_print_temperature} ; Attente de la température de la buse` (pour Cura)<br />
`G28 ; Origines des axes`<br />
`M420 S1 ; Activation du maillage`<br />
`; Descente de la Hotend et passage à la position de départ`<br />
`G1 Z150`<br />
`G1 X-130 Y0 Z0.4 F3000`<br />
`; Extrude environ 40mm en imprimant un arc de 90 degrés`<br />
`G3 X0 Y-130 I130 Z0.3 E40 F1500`<br />
`; Rétraction et déplacement de la hotend vers le haut`<br />
`G92 E0`<br />
`G1 E-1.5 F1800`<br />
`G0 Z0.5`<br />
`G1 E0 F300`

**G-Code de fin :**

`G91 ; Positionnement relatif`<br />
`G1 E-1 F300 ; Rétraction avant déplacement de la hotend vers le haut`<br />
`G1 Z+5 E-5 F6000 ; Déplacement de la hotend vers le haut`<br />
`G28 X0 Y0 ; Origines des axes`<br />
`G90 ; Positionnement absolu`<br />
`G92 E0 ; Réinitialisation de l'extrudeur`<br />
`M104 S0 ; Arrêt de la chauffe de la buse`<br />
`M140 S0 ; Arrêt de la chauffe du plateau`<br />
`M107 ; Arrêt des ventilateurs`<br />
`M84 ; Désactivation des moteurs`

**Comment by atraxxx73** [comment]
Impeccable. Je n etais pas dans le bon readme.md.
Du couo ca rejoint un peu ce que je pensais, mon start G Code ne doit pas être bon du tout.
Je teste ca dans les jours a venir. En tout cas chapeau pour ton taff, l interface est assez hallucinante, et ca change radicalement la becane.
Et le look, on n'en parle pas. Du coup mon soucis n'est pas grand chose.
Merci pour tes reponses, je te redis vite.

**Comment by atraxxx73** [comment]
Bon. J ai eu le temps de tester, donc planéité plateau OK a chaud.
J'ai inséré les G Codes, j avais juste un parametre qui différait par rapport a celui d'origine.
J ai de nouveau essayé, mais malheureusement toujours pareil, la purge fait des petits relevés descente a niveau, puis la tête se releve de 4 ou 5 mm et commence son impression, mais du coup dans le vide.
J ai refais l ABL et le Z offset pour être sûr, mais en vain.

**Comment by atraxxx73** [comment]
Du coup je repasse boucler. Malheureusement retour au firmware d origine, et plus aucun soucis de levage de Z.
Du coup je garde le matos dans un coin pour plus tard, apres un correctif futur, sur le papier c'était quand même top comme système.

Ca serait dommage que je m arrête sur un échec.
Bonne soirée et a plus
