### ISSUE TITLE
[BUG] (short description)

### ISSUE THREAD

**Issue by Elcidz** [Guilouz/BTT-TFT70-SuperRacer#5]
Salut Cyril 

J'ai posté sur la chaine de jstech mais pas de réponse, je suis peut être seul a avoir ce soucis, j ai un problème avec le babystep en 0.01 sa fait rien pour moi pendant le print sa marche nickel pour le réglage du Z. En 0,1 sa fonctionne. Par contre le réglage en 0.01 en prit en compte si je relance un print. En principe ma sr en bien régler tout fonctionne bien (j'ai le LGX et le Tft 70). Ci tu as une solution.
Encore merci pour ton travail et ton temps pour ce super firmware.
Vidéo du pb 👍 
https://www.youtube.com/watch?v=8Rl1ycMgqnQ

### Steps to reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior**

**Actual behavior**

### Additional Information
* Include a ZIP file containing your `Configuration.h` or use [Pastebin](https://pastebin.com/) and paste a link in this issue.
* Provide pictures or links to videos that clearly demonstrate the issue.

**Comment by Guilouz** [comment]
c'est normal que tu ne le "ressente" pas, 0.01 c'est un pas très minime (c'est un 20ème d'une couche en 0.2) et je peux t'assurer qu'il est bien pris en compte.
Tu peux le constater lors du réglage du Z-Offset quand tu es en pas de 0.01 avec une feuille de papier tu peux sentir la pression de la buse sur le plateau.

**Comment by Elcidz** [comment]
Ok mais tu as vu sur la vidéo que j ai poster dans les commentaires je remonte bien mais sa change rien

**Comment by Guilouz** [comment]
Je ne vois pas ta vidéo.

**Comment by Elcidz** [comment]
> Je ne vois pas ta vidéo.

https://youtu.be/8Rl1ycMgqnQ

**Comment by Guilouz** [comment]
Poste ton problème (en anglais) sur le repo BTT directement, voir ce qu'ils en disent parce que là je ne vois pas.

**Comment by Elcidz** [comment]
Pour toi il y a un pb ou pas? Ou s est moi qui spycot ?

**Comment by Guilouz** [comment]
Pour moi les babysteps sont bien pris en compte, suffit de le vérifier en faisant un M503 à la ligne M851, tu dois retrouver ta nouvelle valeur d'offset enregistrée pendant ton print.

**Comment by Elcidz** [comment]
Oui s est bien prit en compte dans le firmware mais comme
Tu le vois dans la vidéo je remonte de 0,4 avec le 0,01 et sa change rien je suis toujours trop bas alors que sa devrait même plus adhérer au bed.
