### ISSUE TITLE
Speed on BTT tft 70 

### ISSUE THREAD

**Issue by Packat10** [Guilouz/BTT-TFT70-SuperRacer#6]
Bonjour 
tout d'abord je ne te remercierais jamais assez pour le travail que tu fais et l'aide apporté 👍👌
Je voulais savoir s'il était possible de rajouter la vision de la vitesse sur l'écran pour le FLsun SR ? 
C'est dommage de ne pas avoir la visu de la vitesse de la machine pendant l'impression. 
A bientôt 🙏

**Comment by Guilouz** [comment]
Ce n'est malheureusement pas possible. Le firmware BTT ne sait qu'interpréter des commandes Marlin et il n'y a aucune commande qui permet d'afficher la vitesse d'impression.

**Comment by Packat10** [comment]
C'est dommage, mais ça me va bien.

Le mar. 12 avr. 2022 à 20:31, Cyril Guislain ***@***.***> a
écrit :
