### ISSUE TITLE
can't install language.ini

### ISSUE THREAD

**Issue by MichaelLehner69** [Guilouz/BTT-TFT70-SuperRacer#7]
-->
### Description

thank you for the great work :) i just installed my tft70 with your latest files from 14-04-2022 
sadly i ran into an issue, i want to add the language_de.ini but it says that there is an invalid keyword issue. same problem with other languages. like language.en.ini. 
can you help me out?

**Comment by Guilouz** [comment]
What firmware do you use ? And what is the model of your screen? GD or not ? I think you use no GD firmware on GD screen.

**Comment by MichaelLehner69** [comment]
you were right, i was looking for the letters GD and did not see them but on the chip i found GigaDevice... thank you  :)
