### ISSUE TITLE
[Q] Neopixel

### ISSUE THREAD

**Issue by Wrathlord12** [Guilouz/BTT-TFT70-SuperRacer#8]
Bonjour , et merci pour ton super travail.

Je recherche comment activer la fonction neopixel via l'écran, j'ai bien configurer le fichier de l'écran, maintenant je pense qu'il faut activer via marlin le firmware la fonction neopixel , sauf que dans le fichier configuration sa parle de "pin" ,j'avoue que je suis un peu perdu.Par avance merci

**Comment by Guilouz** [comment]
Tu cherches à activer les Neopixel de quelle manière ? Via une carte mère SKR qui gère les neopixels ou via le port neopixel de l’écran ?

**Comment by Wrathlord12** [comment]
Bonsoir et merci de ta réponse rapide, j'utilise une flsun sun SR et j'ai installé ton superpack.
Ma carte mère est celle qui a le port USB,microsd et port "type imprimante"
J'ai fait la modification pour l'écran BTT , j'ai activer la fonction neopixel egalement dans marlin et refait la compilation.
Sauf que dans la ligne de code sa me demande sur quel pin est branché le neopixel, sur ce point je cale.
Car rien ne se passe 3et je pense que c'est de la que provient le probleme

**Comment by Guilouz** [comment]
L'activation dans Marlin ne te servira à rien, elle n'est utile que si les Neopixel sont branché sur la CM.
Pour utiliser le port Neopixel sur l'écran, il suffit juste de définir le nombre de LED dans le fichier config.ini du TFT :

Knob LED Pixels (only for TFT28/TFT35_E3/TFT43/TFT50/TFT70 V3.0)
Set the number of LEDs in the strip connected to "Neopixel" port of TFT.
It shares the same signal line as "knob_led". 0 means the default number in TFT hardware.
Greater than 0 means the number of LEDs in the strip.
Value range: [min: 0, max: 200]
**neopixel_pixels:0**

Mais attention l'écran ne permet pas d'alimenter beaucoup de LED, il est donc préférable d'alimenter extérieurement les LED et d'utiliser uniquement le PIN signal du TFT pour piloter les LED.

**Comment by Wrathlord12** [comment]
Merci beaucoup cela fonctionne.Tip top.
